/*
 * This source file was generated by the Gradle 'init' task
 */
package alkewallet;

import java.text.DecimalFormat;
import java.util.Scanner;

import alkewallet.convertidor.ConvertidorMoneda;
import alkewallet.convertidor.ConvertidorMonedaSimple;
import alkewallet.model.Cuenta;
import alkewallet.model.Wallet;

public class WalletApp {

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
        final DecimalFormat df = new DecimalFormat("#,##0.00");
        Cuenta cuenta = new Cuenta(100000); // Saldo inicial
        ConvertidorMoneda convertidor = new ConvertidorMonedaSimple(); // Implementación del convertidor
        Wallet wallet = new Wallet(cuenta, convertidor);

        int opcion;
        do {

            System.out.println("\nMenú de opciones:");
            System.out.println("1: Ver Saldo");
            System.out.println("2: Depositar");
            System.out.println("3: Retirar");
            System.out.println("4: Convertir saldo");
            System.out.println("0: Salir");
            System.out.print("Seleccione una opción: ");
            opcion = scanner.nextInt();

            switch (opcion) {
                case 1:
                    System.out.println("Saldo actual: " + df.format(wallet.getSaldo()) + " CLP");
                    break;
                case 2:
                    System.out.print("Ingrese monto a depositar: ");
                    double montoDeposito = scanner.nextDouble();
                    wallet.depositar(montoDeposito);
                    System.out.println("Nuevo saldo: " + df.format(wallet.getSaldo()) + " CLP");
                    break;
                case 3:
                    System.out.print("Ingrese monto a retirar: ");
                    double montoRetiro = scanner.nextDouble();
                    if (wallet.retirar(montoRetiro)) {
                        System.out.println("Retiro exitoso. Nuevo saldo: " + df.format(wallet.getSaldo()) + " CLP");
                    } else {
                        System.out.println("Fondos insuficientes para el retiro.");
                    }
                    break;
                case 4:

                    System.out.print("Ingrese moneda destino para convertir saldo (USD, EUR, etc.): ");
                    String monedaDestino = scanner.next();
                    double saldoConvertido = wallet.convertirSaldo(monedaDestino);
                    System.out.println("Saldo convertido de CLP a " + monedaDestino + ": " + df.format(saldoConvertido));
                    break;
                case 0:
                    System.out.println("Gracias por usar AlkeWallet. ¡Hasta luego!");
                    break;
                default:
                    System.out.println("Opción no válida. Por favor, seleccione una opción del menú.");
            }

        } while (opcion != 0);

        scanner.close();

    }

}
